//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReWrite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReWrite.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRChat写真をDiscordにアップ - Ver.{currentVersion}.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRChat写真をDiscordにアップ - Ver.{currentVersion}（新しいバージョン {latestVersion} があります！）.
        /// </summary>
        internal static string AppTitleWithUpdate {
            get {
                return ResourceManager.GetString("AppTitleWithUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撮影日時.
        /// </summary>
        internal static string CaptureTimeLabel {
            get {
                return ResourceManager.GetString("CaptureTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord送信エラー.
        /// </summary>
        internal static string DiscordSendErrorMessage {
            get {
                return ResourceManager.GetString("DiscordSendErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord送信失敗.
        /// </summary>
        internal static string DiscordSendFailureMessage {
            get {
                return ResourceManager.GetString("DiscordSendFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discordに送信成功.
        /// </summary>
        internal static string DiscordSendSuccessMessage {
            get {
                return ResourceManager.GetString("DiscordSendSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        internal static string ErrorOccurredMessage {
            get {
                return ResourceManager.GetString("ErrorOccurredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定されたフォルダーが存在しません。.
        /// </summary>
        internal static string FolderNotExistMessage {
            get {
                return ResourceManager.GetString("FolderNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォルダーのパスとWebhook URLを入力してください。.
        /// </summary>
        internal static string FolderPathInputMessage {
            get {
                return ResourceManager.GetString("FolderPathInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHubバージョンチェック中のエラー.
        /// </summary>
        internal static string GitHubVersionCheckError {
            get {
                return ResourceManager.GetString("GitHubVersionCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画像情報.
        /// </summary>
        internal static string ImageInformationTitle {
            get {
                return ResourceManager.GetString("ImageInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRChat画像フォルダパス.
        /// </summary>
        internal static string Label2 {
            get {
                return ResourceManager.GetString("Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 言語/Language/语言/언어.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        internal static string Language_Chinese {
            get {
                return ResourceManager.GetString("Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        internal static string Language_Japanese {
            get {
                return ResourceManager.GetString("Language_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한국어.
        /// </summary>
        internal static string Language_Korean {
            get {
                return ResourceManager.GetString("Language_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログファイルが見つかりません.
        /// </summary>
        internal static string LogFilesNotFoundMessage {
            get {
                return ResourceManager.GetString("LogFilesNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログフォルダーが見つかりません.
        /// </summary>
        internal static string LogFolderNotFoundMessage {
            get {
                return ResourceManager.GetString("LogFolderNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログ解析中のエラー.
        /// </summary>
        internal static string LogParsingErrorMessage {
            get {
                return ResourceManager.GetString("LogParsingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しい画像が検出されました.
        /// </summary>
        internal static string NewImageDetectedMessage {
            get {
                return ResourceManager.GetString("NewImageDetectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しい画像がアップロードされました .
        /// </summary>
        internal static string NewImageUploadedMessage {
            get {
                return ResourceManager.GetString("NewImageUploadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効/無効.
        /// </summary>
        internal static string onoff {
            get {
                return ResourceManager.GetString("onoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メイン.
        /// </summary>
        internal static string Page1 {
            get {
                return ResourceManager.GetString("Page1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook設定.
        /// </summary>
        internal static string Page2 {
            get {
                return ResourceManager.GetString("Page2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送信先の名前.
        /// </summary>
        internal static string servername {
            get {
                return ResourceManager.GetString("servername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 監視開始.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 監視を開始しました.
        /// </summary>
        internal static string StartWatchingMessage {
            get {
                return ResourceManager.GetString("StartWatchingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver. {0} を実行していますが、新しいバージョン {1} があります！.
        /// </summary>
        internal static string UpdateAvailableMessage {
            get {
                return ResourceManager.GetString("UpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップデートの確認.
        /// </summary>
        internal static string UpdateCheckTitle {
            get {
                return ResourceManager.GetString("UpdateCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新をダウンロード.
        /// </summary>
        internal static string UpdateDownloadButtonText {
            get {
                return ResourceManager.GetString("UpdateDownloadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoothでVer.{0}をダウンロードしますか？.
        /// </summary>
        internal static string UpdateDownloadMessage {
            get {
                return ResourceManager.GetString("UpdateDownloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ワールド名を検出.
        /// </summary>
        internal static string WorldNameDetectedMessage {
            get {
                return ResourceManager.GetString("WorldNameDetectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ワールド名.
        /// </summary>
        internal static string WorldNameLabel {
            get {
                return ResourceManager.GetString("WorldNameLabel", resourceCulture);
            }
        }
    }
}
